
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 26 18:21:18 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Listado_no = 33;
  public static final int Or = 38;
  public static final int Op_booleano = 36;
  public static final int Llave_c = 15;
  public static final int Exponente = 18;
  public static final int Llave_a = 14;
  public static final int If = 3;
  public static final int Default = 41;
  public static final int Set = 12;
  public static final int Elseif = 34;
  public static final int Else = 35;
  public static final int Menor = 11;
  public static final int Puts = 13;
  public static final int Break = 43;
  public static final int Corchete_c = 20;
  public static final int Corchete_a = 16;
  public static final int Mayor = 27;
  public static final int Then = 4;
  public static final int Proc = 45;
  public static final int Return = 46;
  public static final int While = 5;
  public static final int Division = 10;
  public static final int Listado_si = 32;
  public static final int Cadena = 26;
  public static final int For = 44;
  public static final int EOF = 0;
  public static final int P_coma = 21;
  public static final int No_igual_que = 31;
  public static final int Not = 39;
  public static final int And = 37;
  public static final int error = 1;
  public static final int Mayor_igual = 29;
  public static final int Switch = 40;
  public static final int Linea = 2;
  public static final int Dolar = 25;
  public static final int Igual_que = 30;
  public static final int ERROR = 48;
  public static final int Continue = 42;
  public static final int Expr = 17;
  public static final int Menor_igual = 28;
  public static final int Incr = 47;
  public static final int Identificador = 22;
  public static final int Resta = 8;
  public static final int Porcentaje = 19;
  public static final int Multiplicacion = 9;
  public static final int Numero = 23;
  public static final int Suma = 7;
  public static final int Igual = 6;
  public static final int Comillas = 24;
}

